version: '2'
services:
  db:
     image: mysql:5.7
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     ports:
      - 3306:3306
     volumes:
        - ./mysql_data:/var/lib/mysql
     environment:
        MYSQL_ROOT_PASSWORD: root
  admin:
     image: adminer
     restart: always
     ports:
       - 8080:8080